### ISSUE TITLE
How to define custom-patches using multiple repos?

### ISSUE THREAD

**Issue by cubagithub** [RattlesnakeOS/community_patches#11]
I'm trying to include patches in two separate repos as a list. 

When I try to add two sets of 'patches' I get an error about defining it twice. When I try to define both as a listin my TOML:

```
patches = [
        "00002-microg-sigspoof.patch",
        "00001-global-internet-permission-toggle.patch",
]
repo = [
        "https://github.com/RattlesnakeOS/microg",
        "https://github.com/RattlesnakeOS/community_patches",
]
```

I get this processed format:

custom-patches:
- patches:
  - 00002-microg-sigspoof.patch
  - 00001-global-internet-permission-toggle.patch
  repo:
  - https://github.com/RattlesnakeOS/microg
  - https://github.com/RattlesnakeOS/community_patches
custom-prebuilts:
- modules:
  - GmsCore
  - GsfProxy
  - FakeStore
  - com.google.android.maps.jar
  repo: https://github.com/RattlesnakeOS/microg

And I get this warning:
WARN[0000] You are using an untrusted repository () for patches - this is risky unless you own the repository
✗ Do you want to continue :

What is the correct way to do this?

**Comment by dan-v** [comment]
The instructions show how to properly add it to your config file: https://github.com/RattlesnakeOS/microg#how-to. You don't combine it into a single entry, you make separate entries.  So it would look something like this:

```
[[custom-patches]]
  repo = "https://github.com/RattlesnakeOS/community_patches"
  patches = [
      "00001-global-internet-permission-toggle.patch", "00002-global-sensors-permission-toggle.patch",
  ]

[[custom-patches]]
patches = ["00002-microg-sigspoof.patch"]
repo = "https://github.com/RattlesnakeOS/microg"

[[custom-prebuilts]]
modules = ["GmsCore","GsfProxy","FakeStore","com.google.android.maps.jar"]
repo = "https://github.com/RattlesnakeOS/microg"
```

**Comment by cubagithub** [comment]
Thank you for the help. Actually I read that page but it's not 100% clear there either, because only one custom-patches repo is defined in that example.
 
Initially I tried adding two patches or repo lines under the one custom-patches entry, but I got a warning that I couldn't define patches twice.
