### ISSUE TITLE
Global sensor permissions toggle patch fails

### ISSUE THREAD

**Issue by madelponte** [RattlesnakeOS/community_patches#15]
Fails to patch on walleye rattlesnakeos version 10.0.10.

>2020-08-28 12:37:52: Applying patch 00004-global-sensors-permission-toggle.patch
patching file frameworks/base/core/java/android/content/pm/PackageParser.java
Hunk #1 succeeded at 284 with fuzz 1 (offset 6 lines).
patching file frameworks/base/core/res/AndroidManifest.xml
Hunk #1 succeeded at 1310 (offset 181 lines).
patching file frameworks/base/core/res/res/values/strings.xml
Hunk #1 succeeded at 797 with fuzz 2 (offset 50 lines).
Hunk #2 succeeded at 1096 (offset 35 lines).
patching file frameworks/base/services/core/java/com/android/server/pm/permission/PermissionManagerService.java
Hunk #1 FAILED at 1333.
1 out of 1 hunk FAILED -- saving rejects to file frameworks/base/services/core/java/com/android/server/pm/permission/PermissionManagerService.java.rej
patching file frameworks/native/libs/sensor/Sensor.cpp
Hunk #1 succeeded at 59 (offset 7 lines).
can't find file to patch at input line 110
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:

>|diff --git a/packages/apps/F-Droid/app/src/main/java/org/fdroid/fdroid/installer/ApkVerifier.java b/packages/apps/F-Droid/app/src/main/java/org/fdroid/fdroid/installer/ApkVerifier.java
>|index e59ba367..c6edd542 100644
>|--- a/packages/apps/F-Droid/app/src/main/java/org/fdroid/fdroid/installer/ApkVerifier.java
>|+++ b/packages/apps/F-Droid/app/src/main/java/org/fdroid/fdroid/installer/ApkVerifier.java

**Comment by dan-v** [comment]
@madelponte unfortunately there are only a few documented patches in the README that are working with 10.0.

**Comment by dan-v** [comment]
Closing this as latest is 11.0 now. Still need a contribution for sensor patch though.
